// Generated by https://quicktype.io

export interface APIResponse {
    data:  string;
    usage: any;
}

export interface Usage {
    prompt_tokens:     number;
    completion_tokens: number;
    total_tokens:      number;
}
